nodeLinker: node-modules

packageExtensions:
  "@linaria/babel-preset@*":
    dependencies:
      "@babel/plugin-proposal-export-namespace-from": ^7.16.0
      "@babel/plugin-transform-modules-commonjs": ^7.16.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.3.cjs
